# The URL the site will be built for
base_url = "https://ocp.xyz"
title = "Outside Context Labs"
compile_sass = true
build_search_index = false
description = "Outside Context Labs"
default_language = "en"

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
